[meta]
    total = 1
    size =  '20Mb'
[file]
    [file.1]
    fid =            1
    name =          'test'
    cover =         './assets/img/2291381582291.svg'
    creation_time = '20210808121212'
    brief =         '文件描述'
    store =         'direct:0'